### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Oluwadamilareolusakin**
Complete the development of the mint.com replica site.

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Hi there team.
You did a great work in this project 👍. But before its ready to merge to master we need to do some changes to make the project in line with Microverse Guidelines. The changes are:
*All these changes are from the 'Signup.html'.

- [ ] It must show the Quickbooks logo and text (logo on the left, text on the right). You are using the mint logo 2 times.

- [ ] Your input for the email must use the 'email' value for the attribute 'type'

- [ ] Your input for the phone must use the 'tel' value for the attribute 'type'

- [ ] The bottom part of your form must match the original style.
image

- [ ] Your HTML file (signup.html), is missing the ' l ' in the end.

Please kindly make these changes and submit for code review again.

**Comment by Oluwadamilareolusakin** [comment]
All Changes requested have been made

**Comment by maelfosso** [comment]
Hello coders,

You did a really nice job. But before moving forward, there are few things to change about the Sign Up page.

- [ ] The products row is not the image. For each product, it's the logo + the text.

- [ ] For the phone number, the input type should **tel**

- [ ] I suggest you to use the `<nav>` tag for the top part, the `<main>` tag for the part between the nav and the footer.

Please make those changes and submit a new code review request.

**Comment by Oluwadamilareolusakin** [comment]
All changes have been made

**Comment by Ispirett** [comment]
Hey, folks really great work with your changes for this project :100: Final adjustments that will just make your project shine and correct minor issues.
- [ ] Try to get get your sign up button to look more like the original site. **Hint** use CSS **height**  ** width** and **margin-top** attributes.
- [ ] Remove the extra text from the logo or you can try to find a better logo.

**Comment by Oluwadamilareolusakin** [comment]
@Ispirett All changes have been made to the entire site, thank you for your helpful comments

**Comment by Oghenebrume50** [comment]
Hello coders,  you guys have really done a great job.

**Good to know**
Learn more on CSS specificity, and use less of ids for styling, check out this [link] (https://dev.to/claireparkerjones/reasons-not-to-use-ids-in-css-4ni4) to know why
You can merge to master and submit this project. Happy Coding

**Pull request merged**
